- .changeset/nine-grapes-play.md
- README.md
- index.js
- package.json
> fill out missing properties in package.json

- .changeset/four-planets-notice.md
- README.md
- src/koa-middleware.js
- test/counterfact.test.js
- test/dispatcher.test.js
- test/koa-middleware.test.js
> support for setting the HTTP status code

- .changeset/orange-cherries-hang.md
> Github actions seems to be stuck on the release PR. 

- .changeset/cool-ads-jam.md
- README.md
- src/registry.js
- test/dispatcher.test.js
- Better error handling when a route is not found
- minor updates to README
fixes #20
> 20 handle unknown routes by returning 404

- .changeset/spicy-items-begin.md
- README.md
- demo-ts/context/context.ts
- demo-ts/routes/#types.ts
- demo-ts/routes/count.ts
- demo-ts/routes/hello/#types.ts
- demo-ts/routes/hello/[name].ts
- demo/routes/count.js
- demo/routes/hello/[name].js
- src/counterfact.js
- src/dispatcher.js
- src/registry.js
- test/counterfact.test.js
- test/dispatcher.test.js
- test/module-loader.test.js
- test/registry.test.js
- renamed store to context
- add a second argument to counterfact() for setting the initial context
> 44 user defined context instead of store

- .changeset/healthy-snails-confess.md
I need the tools object to be in the released version of Counterfact so I can use it in the generated code I'm working on now.
> create a release for tools

- .changeset/famous-cheetahs-heal.md
- README.md
- bin/counterfact.js
- package.json
- src/typescript-generator/generate.js
- CLI for generator
- minor updates to readme
> changeset for generator

- src/typescript-generator/operation-coder.js
- test/typescript-generator/__snapshots__/operation-coder.test.js.snap
- test/typescript-generator/operation-coder.test.js
I don't like that I had to use snapshot testing but have to start somewhere. Will probably keep these snapshot tests around  as integration tests but refactor later into small methods that can be tested in isolation.
> unit tests for OperationCoder

- .changeset/clean-drinks-report.md
- package.json
- src/typescript-generator/parameters-type-coder.js
- src/typescript-generator/requirement.js
- test/typescript-generator/__snapshots__/operation-type-coder.test.js.snap
- test/typescript-generator/__snapshots__/parameters-type-coder.test.js.snap
- test/typescript-generator/__snapshots__/tools.coder.test.js.snap
- test/typescript-generator/operation-type-coder.test.js
- test/typescript-generator/parameters-type-coder.test.js
- test/typescript-generator/schema-type-coder.test.js
- test/typescript-generator/tools.coder.test.js
- characterization tests for OperationTypeCoder
- characterization tests for SchemaTypeCoder
- characterization tests for ParametersTypeCoder
- unit test for ToolsCoder
- fix yarn generate
> unit tests for coders

- .changeset/kind-jars-bathe.md
- .changeset/tiny-walls-matter.md
- src/typescript-generator/coder.js
- src/typescript-generator/generate.js
- src/typescript-generator/operation-coder.js
- src/typescript-generator/repository.js
- src/typescript-generator/schema-coder.js
- test/typescript-generator/__snapshots__/end-to-end.test.js.snap
- test/typescript-generator/end-to-end.test.js
- test/typescript-generator/petstore.yaml
- test/typescript-generator/schema-coder.test.js
I cheated a little bit by creating a massive snapshot test, but it uncovered a couple of bugs and provides the air support needed for refactoring and writing more precise unit tests.
> end-to-end test and a couple of bug fixes

- .changeset/twenty-hairs-lick.md
- src/typescript-generator/schema-type-coder.js
- test/typescript-generator/__snapshots__/end-to-end.test.js.snap
- test/typescript-generator/schema-type-coder.test.js
> handle additionalProperties in JSON Schema

- .changeset/modern-ducks-taste.md
- .eslintrc.cjs
- docs/usage.md
- package.json
- src/dispatcher.js
- test/dispatcher.test.js
- yarn.lock
Counterfact will use the one that best matches the request's accept header.
If there are no matches it will return a 406 error.
> ability to return multiple content types / bodies

- .changeset/early-cougars-argue.md
- demo/paths/hello/{name}.js
- src/dispatcher.js
- src/response-builder.js
- test/dispatcher.test.js
- test/response-builder.test.js
- response builder object
- pass a response builder object in the request
- update the demo app to use the response object
- changeset for response builder API
> 133 response builder fluent api

- .changeset/blue-pillows-study.md
- demo-ts/yarn.lock
- jest.config.json
- package.json
- src/types.d.ts
TypeScript type definition for the response argument.
> response builder type

- src/typescript-generator/operation-coder.js
- src/typescript-generator/operation-type-coder.js
- src/typescript-generator/parameters-type-coder.js
- src/typescript-generator/requirement.js
- src/typescript-generator/response-type-coder.js
- src/typescript-generator/schema-coder.js
- src/typescript-generator/schema-type-coder.js
- test/typescript-generator/requirement.test.js
> adds a requirement.get() function for going down one level without escaping

- .changeset/soft-ants-allow.md
- bin/counterfact.js
- package.json
- src/counterfact.js
- src/read-file.js
- src/typescript-generator/specification.js
- test/typescript-generator/specification.test.js
- yarn.lock
load an OpenAPI document from either a path or an http[s] URL
> 104 load an openapi spec from the web

- README.md
- update README with latest status
- minor edits to readme
> update readme 09 29

- README.md
Rework the README. It's clearly incomplete but a step forward so I'm going to go ahead and merge.
> refined readme

- docs/usage.md
> update usage doc

- .changeset/old-ants-smoke.md
- bin/counterfact.js
- jest.config.json
- src/start.js
- test/start.test.js
When you run the CLI with the `--open` flag it opens to this page. It's not pretty but it's a start.
> MVP of a landing page

- .changeset/fifty-steaks-melt.md
- .changeset/polite-mails-tease.md
- .vscode/settings.json
- bin/counterfact.js
- docs/usage.md
- src/server/module-loader.js
- src/typescript-generator/coder.js
- src/typescript-generator/context-coder.js
- src/typescript-generator/script.js
- test/server/module-loader.test.js
- test/typescript-generator/__snapshots__/end-to-end.test.js.snap
- A bunch of fancy stuff with the REPL
- rename .ts to $.context.ts for consistency
- Add REPL to the usage docs
> improvements to REPL and $.context ojbect

- .changeset/strong-peas-judge.md
- package.json
- src/server/module-loader.js
- yarn.lock
- use esbuild loader instead of adding .mjs files to the drive
- ts-node via loader
> use ts node

- .changeset/empty-jars-change.md
- bin/counterfact.js
- docs/quick-start.md
- docs/usage.md
- package.json
- src/typescript-generator/context-coder.js
- test/typescript-generator/__snapshots__/end-to-end.test.js.snap
- tsconfig.json
- use esbuild loader instead of adding .mjs files to the drive
- ts-node via loader
- fix hashbang
- okay, I give up, you have to have ts-node installed globally
> ts node fix

- .github/workflows/release.yaml
https://github.com/changesets/action/issues/187#issuecomment-1220791777
> use a PAT instead of GITHUB_TOKEN for changesets

- .changeset/twenty-eggs-sleep.md
- src/typescript-generator/parameters-type-coder.js
- test/typescript-generator/__snapshots__/end-to-end.test.js.snap
- test/typescript-generator/__snapshots__/operation-type-coder.test.js.snap
- test/typescript-generator/__snapshots__/parameters-type-coder.test.js.snap
Related to this Issue https://github.com/pmcelhaney/counterfact/issues/453, cc @pmcelhaney
> Fix: Found an error when headers name contains `-`

- .changeset/big-cycles-impress.md
- bin/counterfact.js
- package.json
to see verbose logs set the environment variable `DEBUG=counterfact`
> add verbose logging

- .changeset/cool-bananas-watch.md
- .github/workflows/debug-windows.yaml
- bin/counterfact.js
- src/typescript-generator/generate.js
- src/typescript-generator/specification.js
- src/util/read-file.js
- a bunch more logging to figure out what's going on with Windows
- try to debug Windows using Github runner
> more logging

- test/lib/with-temporary-files.js
Doesn't seem like it matters right now but may save some headaches in the future.
> fix a backslash issue in a unit test

- .changeset/nine-pandas-shout.md
- bin/counterfact.js
- src/server/module-loader.js
- src/server/registry.js
- src/server/start.js
- src/typescript-generator/repository.js
> fix broken URLs on the start page in Windows

- README.md
- docs/quick-start.md
Rewrote the README to focus less on features and more on the problem Counterfact solves.
> Rewrite readme

- .changeset/selfish-cameras-wave.md
- src/server/module-tree.ts
- test/server/module-tree.test.ts
> fix(server): Trailing slashes on an endpoint #703

- .changeset/blue-dots-deny.md
- src/typescript-generator/repository.js
- remove dumb if statement
- remove dumb if statement
> always copy types.d.ts

- .changeset/gold-dolls-decide.md
- bin/counterfact.js
> exit gracefully if running Node < 17

- .changeset/strange-flowers-speak.md
- src/typescript-generator/repository.js
- test/typescript-generator/repository.test.js
- fix another case of backlashes instead of slashes on Windows, fixes #788
- changeset for backlash fix
> fix backslash in context import on Windows

- .changeset/slow-boxes-share.md
- docs/usage.md
- src/server/registry.ts
- src/server/types.d.ts
- src/typescript-generator/operation-type-coder.js
- test/typescript-generator/__snapshots__/generate.test.ts.snap
- test/typescript-generator/__snapshots__/operation-type-coder.test.js.snap
> add $.x, a loosely typed alias of $

- .changeset/two-crews-shake.md
- src/server/types.d.ts
- src/typescript-generator/operation-type-coder.js
- src/typescript-generator/response-type-coder.js
- test/server/dispatcher.test.ts
- test/typescript-generator/__snapshots__/generate.test.ts.snap
- test/typescript-generator/__snapshots__/operation-type-coder.test.js.snap
- test/typescript-generator/response-type-coder.test.js
One day I will document how this crazy type system works.
> optional headers type safety

- .changeset/twelve-frogs-attack.md
- docs/usage.md
Adds a section to the usage guide for installing CF as a dependency.
> chore(docs): Add documentation for running Counterfact as a dependency

- docs/usage.md
Hi, I love this tool very much!  Thank for your sharing. 
And I found a few mistakes in the docs. So I open this PR.
-----
<a href="https://stackblitz.com/~/github.com/yangsimin/counterfact/tree/yangsimin/patch-88531"><img src="https://developer.stackblitz.com/img/review_pr_small.svg" alt="Review PR in StackBlitz" align="left" width="103" height="20"></a> _Submitted with [StackBlitz](https://stackblitz.com/~/github.com/yangsimin/counterfact/tree/yangsimin/patch-88531)._
> fix(docs): update usage.md

- eslint.config.cjs
> lint *.test.ts files

- .changeset/grumpy-eels-stick.md
- README.md
- package.json
- **simplified, to the point README file**
- **no border on the logo**
- **remove unwanted horizontal lines on GitHub**
- **typo**
- **move menu to the bottom**
- **add some space below the logo**
- **move badges to the bottom**
- **minor tweaks to README and package.json**
- **changeset so package.json changes will be published**
> new readme
