- .eslintrc.cjs
- .husky/post-commit
- package.json
- yarn.lock
Normally ESLint is run as a pre-commit hook.
But having a commit blocked because of lint errors can be annoying sometimes.
Sometimes I'm okay with things being broken temporarily; CI will run ESLint
and prevent the offending code from landing on main.
But then there's a new problem. Code is committed and pushed, and then CI
fails because of a silly lint error. I'm giving the post-commit hook at try
so I can find out immediately if the code I just pushed will break CI.
Let's see how this goes...
> Install husky and run eslint after commits

- .changeset/gentle-kangaroos-switch.md
- .eslintrc.cjs
- src/dispatcher.js
- src/tools.js
- test/dispatcher.test.js
- test/tools.test.js
It provides some useful functionality:
- `tools.oneOf(array)` returns a random item from an array (used for selecting a random example from a an OpenAPI schema)
- `tools.accepts(contentType)` identifies whether the request accepts a particular content type
> Add a tools object that will be provided to the request

- .changeset/blue-mangos-talk.md
- .devcontainer/Dockerfile
- .devcontainer/base.Dockerfile
- .devcontainer/devcontainer.json
- .vscode/settings.json
- README.md
Code to add a basic devcontainer.
I left the configuration pretty light. I've also left the `.vscode` directory in place for those that don't want (or can't) use the container. We'll need to keep them in sync.
> Add basic devcontainer.

- demo/README.md
- demo/index.js
- demo/routes/user.js
- package.json
- src/dispatcher.js
- test/dispatcher.test.js
- yarn.lock
This is a very basic implementation of headers in Counterfact. If we go with this route, you can send headers in any route, and get them returned to you on the response. 
I added an example implementation under `demo/user.js` to decode a JWT sent in an authorization header. 
There wasnt much to actually test here since the Counterfact side is really simple. 
closes #21
> Add headers concept to Counterfact, add example user route

- .devcontainer/devcontainer.json
- .vscode/settings.json
Some of the ESLint rules depend on the filesystem and can be very slow. If those rules are not fixable, there's no point in running them when formatting on save. 
I'm not 100% sure this is necessary but I _think_ it helped fix really slow saves in my environment.
> performance tuning for automatic formatting in VSCode via ESLint

- .changeset/purple-cups-greet.md
- src/dispatcher.js
- test/dispatcher.test.js
- remove the reducer function, an early idea that was never documented
- clarification in test description
- support 'hello world' scenario returning just a string instead of a response object
> 128 simple api for simple response

- jest.config.json
Babel wasn't working. While the V8 provider is still considered experimental, it seems to be where things are going, and it works.
https://jestjs.io/blog/2020/01/21/jest-25#v8-code-coverage
> change Jest coverageProvider to "v8"

- .changeset/plenty-peaches-sneeze.md
- demo/openapi.yaml
- src/counterfact.js
- src/dispatcher.js
- src/registry.js
- src/response-builder.js
- test/counterfact.test.js
- test/dispatcher.test.js
- test/lib/with-temporary-files.js
- test/response-builder.test.js
Counterfact is now able to read an OpenAPI document and use it to generate a random response.
```js
export function GET ({response}) {
return response[200].random();
}
```
> response.random() 

- .changeset/lucky-starfishes-fail.md
- .github/workflows/ci.yaml
- .github/workflows/coveralls.yaml
- .gitignore
- README.md
- bin/counterfact.js
- package.json
- src/counterfact.js
- src/module-loader.js
- src/start.js
- src/transpiler.js
- src/typescript-generator/init.js
- test/counterfact.test.js
- test/transpiler.test.js
- Streamline the CLI. This is not working yet because I need to transform the TS files
- transpile Typescript on the fly
- more unit test concurrency shenanigans
- update generate scripts in package.json
- add changeset
- Bring back the generate, start, and init commmands. The one command to rule them all is now under 'go'
- update the changelog to mention the go command
- Update README to reflect current status and (in)stability
- Make sure Jest exits in CI even if there are open handles
- just trying to get CI to run
> go command

- .eslintrc.cjs
- package.json
- yarn.lock
These changes are only intended to make it easier for me to test / bootstrap by generating code and putting in the `./out` directory instead of importing Counterfact from another project.
- make Counterfact a depenency of itself
- tell ESLint to ignore the out directory
> counterfact depends on counterfact

- .changeset/eighty-dogs-judge.md
- src/typescript-generator/schema-type-coder.js
- test/typescript-generator/__snapshots__/end-to-end.test.js.snap
- test/typescript-generator/schema-type-coder.test.js
- schema object properties are optional by default
- When encoding JSON schema in TypeScript, mark object properties as optional unless they are required
- add changeset for optional properties
> 115 all properties are treated as required

- package.json
- yarn.lock
the package depending on (an old version of) itself is a temporary hack that should be removed by 1.0
> update counterfact's dependency on counterfact so it doesn't break the release pipeline

- README.md
- _config.yaml
It works fine on Github itself, but Markdown inside tags isn't parsed on the site (counterfact.dev)
> trying to get Github pages to parse Markdown

- src/typescript-generator/generate.js
- src/typescript-generator/operation-coder.js
- src/typescript-generator/operation-type-coder.js
- src/typescript-generator/print-object-from-entries.js
- src/typescript-generator/printers.js
- src/typescript-generator/requirement.js
- src/typescript-generator/response-type-coder.js
- test/typescript-generator/__snapshots__/end-to-end.test.js.snap
- test/typescript-generator/integration.test.js
- test/typescript-generator/requirement.test.js
- test/typescript-generator/response-type-coder.test.js
- change flatMap signature so the callback is (value, key) => result
- change requirement.map signature so the callback is (value, key) => result
- now that map() is refactored, flatMap() can got back to delegating to it
- change requirement.forEach signature so the callback is (value, key) => result
- refactor responseTypeCoder.normalizeStatusCode()
- simplify ResponseTypeCoder.buildContentObjectType
- simplify responseTypeCoder.buildHeaders
- rename variable for consistency with buildHeaders
- new printObjectFromEntries() function
- use printObjectFromEntries() in responseTypeCoder.buildHeaders()
- refactor ResponseTypeCoder so few arguments are passed around
- teasing apart ASTs and printers a little bit at a time
Some things I'm thinking about next:
1. There's an opportunity now for …
> saturday refactoring

- .changeset/shaggy-snakes-trade.md
- package.json
- src/server/counterfact.js
- src/typescript-generator/generate.js
- src/typescript-generator/operation-coder.js
- src/typescript-generator/operation-type-coder.js
- src/typescript-generator/parameters-type-coder.js
- src/typescript-generator/repository.js
- src/typescript-generator/requirement.js
- src/typescript-generator/response-type-coder.js
- test/typescript-generator/__snapshots__/end-to-end.test.js.snap
- test/typescript-generator/__snapshots__/operation-type-coder.test.js.snap
- test/typescript-generator/__snapshots__/parameters-type-coder.test.js.snap
- test/typescript-generator/parameters-type-coder.test.js
- test/typescript-generator/requirement.test.js
Add support for OpenAPI 2. This is hacky. More unit tests are needed. I should look at the actual spec version rather than duck type. 
Maybe create subclasses of each Coder for OpenAPI 2. That implies a factory for creating coders instead of calling their constructors directly. That may be a better design in the long run, but I don't think I want to deal with that right now. 
- add a shortcut for generating (testing) pet store v2
- support for OAS2 parameter, where there is not a separate schema object
- generate a default response for an OAS2 operation
- refactoring caused whitespace changes in the snapshot
- generate the response type for OAS2
- move the code to copy response-builder-factory.ts into generate()
- move copying response-builder-factory.ts into repository.js
- refactoring …
> OpenAPI 2 support

- .changeset/short-plums-grin.md
- src/server/response-builder.js
This stuff gives me a headache. The default export from JSONSchemaFaker is marked deprecated. [Long story](https://github.com/json-schema-faker/json-schema-faker/issues/712). 
I tried to switch to the new, non-deprecated named export, and that worked fine until I tried to install Counterfact and use it rather than run it directly from the package. 
```
npx counterfact@latest https://petstore3.swagger.io/api/v3/openapi.json api --open
file:///Users/pmcelhaney/.npm/_npx/e8d1761dc3fb6aab/node_modules/counterfact/src/server/response-builder.js:1
import { JSONSchemaFaker } from "json-schema-faker";
^^^^^^^^^^^^^^^
SyntaxError: Named export 'JSONSchemaFaker' not found. The requested module 'json-schema-faker' is a CommonJS module, which may not support all module.exports as named exports. …
```
> change the way JSONSchemaFaker is imported so it works with CJS

- .changeset/blue-birds-perform.md
- .gitignore
- src/typescript-generator/operation-type-coder.js
- src/typescript-generator/specification.js
fix an issue where top-level produces in OpenAPI 2 was not working
> fix produces error

- .changeset/grumpy-peaches-repair.md
- .eslintrc.cjs
- bin/counterfact.js
- package.json
reverts a change that happened by mistake because I was trying to comply with the "n/shebang" eslint rule
> fix an issue where ts-node was not being used

- .changeset/fast-planes-sell.md
- src/typescript-generator/script.js
- test/typescript-generator/script.test.js
Fixes the `importStatements` logic to avoid lint errors with relative paths.
> TypeScript Generator relative path fix

- .changeset/eight-papayas-melt.md
- src/server/registry.js
- test/server/registry.test.js
If APIs are deployed on Windows, they may not be picky about URLs have the correct case. This change makes Counterfact work the same way. `GET /foo` and `GET /FOO` are the same. 
At some point, we might want to add a setting so that "strict" mode can be enabled. For now, I think the majority of people will either benefit from the change or won't notice any difference. 
See https://github.com/pmcelhaney/counterfact/discussions/537
> make paths case-insensitive

- .github/workflows/ci.yaml
- src/server/transpiler.ts
- test/server/transpiler.test.ts
The "transpiler... discovers a new file and transpiles it" test was failing on all PRs. Of course when I try to debug it passes. Let's just merge this and see what happens with the other PRs.
> debug a flaky test on Windows

- .changeset/slow-kangaroos-move.md
- .github/workflows/ci.yaml
- README.md
- package.json
Version 0.26.0 was not working because it's trying to run patch-package after install, and the command patch-package is "not found". The only package that's being patched is a dev dependency so it's not needed anyway.
> no patch package after install

- .changeset/small-snakes-brush.md
- src/server/dispatcher.ts
- test/server/dispatcher.test.ts
fixes #585 where the dispatcher needs the matchedPath passed to the contextRegistry find method so it does not include the api basePath.
> fix(server): correct dispatcher request method to use matchedPath

- .changeset/famous-humans-juggle.md
- src/server/dispatcher.ts
- src/server/koa-middleware.ts
- src/server/registry.ts
- test/server/koa-middleware.test.ts
fix #593
Corrects the logic in `koa-middleware.js` to properly add any custom response headers. Also fleshes out some of the types in `dispatcher` to be more explicit about the response types coming to the `koa-middleware`.
> fix(server): fixes Custom headers not being correctly added from the response builder #593

- .changeset/afraid-bugs-sniff.md
- bin/counterfact.js
- src/migrations/0.27.js
- src/server/context-registry.ts
- src/typescript-generator/context-coder.js
- src/typescript-generator/context-type-coder.js
- src/typescript-generator/generate.js
- src/typescript-generator/operation-type-coder.js
- test/server/module-loader.test.ts
- test/typescript-generator/__snapshots__/generate.test.ts.snap
- test/typescript-generator/__snapshots__/operation-type-coder.test.js.snap
- test/typescript-generator/context-coder.test.js
- test/typescript-generator/context-type-coder.test.js
Fixes an issue where each directory under paths had its own copy of the context object. As it stands, this is a breaking change: existing `$.context.ts` files won't work. Need to add a migration to detect and fix legacy files. 
fixes #604
> fix root context not shared

- .changeset/wild-bees-hammer.md
- src/server/response-builder.ts
> configure json-schema-faker to create between 0 and 20 items 

- .github/workflows/renovte-changeset.yaml
- renovate.json
In theory, this will cause the changelog to be updated when Renovate updates dependencies.
> add changesets to Renovate updates

- .changeset/big-teachers-mix.md
- src/server/dispatcher.ts
- src/server/registry.ts
- src/server/response-builder.ts
- src/server/types.d.ts
- src/typescript-generator/operation-coder.js
- src/typescript-generator/operation-type-coder.js
- test/server/dispatcher.test.ts
- test/server/response-builder.test.ts
- test/typescript-generator/__snapshots__/generate.test.ts.snap
- test/typescript-generator/__snapshots__/operation-type-coder.test.js.snap
- always return a response even if it has no content
- fix the type for random()
- respond with 500 error if the handler function doesn't return anything
- changeset for ensuring a handler function always returns a response
> a handler function should always return a response

- .changeset/sharp-comics-end.md
- docs/context-change.md
- docs/usage.md
- src/server/context-registry.ts
- src/server/module-loader.ts
- src/typescript-generator/context-type-coder.js
- src/typescript-generator/generate.js
- test/server/module-loader.test.ts
- test/typescript-generator/__snapshots__/generate.test.ts.snap
- test/typescript-generator/context-type-coder.test.js
A minor breaking change in the way context objects are defined.
This change was made because putting a `$` in a file name can be confusing in Mac/Linux/Unix systems.
```ts
class Context {
// ...
}
export default new Context();
```
```ts
export class Context {
// ...
}
```
In the future, the context class will be able to have a constructor that takes one argument, an instance of the _parent_ context.
```ts
// paths/accounts/_context.ts
import { CounterfactContext } from "../../types.ts";
export class Context extends CounterfactContext {
constructor(registry) {
this.mainContext = registry.find("/");
this.productsContext = registry.find("/products");
}
// ...
}
```
> Rework context

- .changeset/sweet-nails-itch.md
- src/server/dispatcher.ts
- test/server/dispatcher.test.ts
Updates the Dispatcher logic to allow requests that contain the OpenApi `basePath` at the root of the path. For example, if the `basePath` is `/myApi` and a consumer of the mock service makes a call to `/myApi/someEndpoint` the present code will give a 404. This change allows handling of that request just as if the consumer called `/someEndpoint`. Some consumers in a webpack proxy situation are sending the `basePath` in the request path and this allows handling that situation.
> feat(server): Add dispatcher logic to allow handling requests container OpenApi basePath

- .changeset/quiet-starfishes-hang.md
- src/server/types.d.ts
- src/typescript-generator/operation-type-coder.js
- test/typescript-generator/__snapshots__/generate.test.ts.snap
- test/typescript-generator/__snapshots__/operation-type-coder.test.js.snap
The return type for operations `GET()`, `POST()`, etc. previously included `{}`, which meant that basically anything would type check.
This changes ensures the return type is a complete response. It either contains all of the headers and content types specified by OpenAPI or it's something like `random()` where the actual type is hard to determine at compile-time but we know it will work at run-time.
> strengthen the return type of an operations

- src/server/types.d.ts
If the OpenAPI spec specifies a response header, this should type check. 
```ts
export const GET: HTTP_GET = ($) => {
return $.response[200].random();
}
```
Currently the `random()` function doesn't generate response headers, but it should. 
If you want to specify the header value, this should work.
```ts
export const GET: HTTP_GET = ($) => {
return $.response[200].header("x-test", "foo").random();
}
```
And this should work too (theoretically), but it currently does not type check.
```ts
export const GET: HTTP_GET = ($) => {
return $.response[200].random().header("x-test", "foo");
}
```
This is a quick fix so I can get a release out. Going to work on making all this stuff right next.
> temporary workaround so random() type checks even if a header is missing

- src/typescript-generator/generate.js
- src/typescript-generator/operation-coder.js
- src/typescript-generator/operation-type-coder.js
- test/typescript-generator/operation-coder.test.js
- test/typescript-generator/operation-type-coder.test.js
That makes the code a bit easier to follow, particularly in generate.js
> pass requestMethod to the constructor of OperationCoder / OperationTypeCoder

- .changeset/bright-rockets-cheer.md
- src/server/dispatcher.ts
- test/server/dispatcher.test.ts
Updates `dispatcher` class to ignore case when finding operations for a given path. This brings it in line with the already case-insensitive logic present in the registry.
> fix(dispatcher): Fix dispatcher.findOperation to use case insensitive match

- .changeset/sharp-kangaroos-build.md
- .eslintrc.cjs
- docs/usage.md
- openapi-example.yaml
- src/server/dispatcher.ts
- src/server/koa-middleware.ts
- src/server/registry.ts
- src/typescript-generator/generate.js
- src/typescript-generator/operation-coder.js
- src/typescript-generator/operation-type-coder.js
- test/server/koa-middleware.test.ts
- test/typescript-generator/__snapshots__/generate.test.ts.snap
- test/typescript-generator/__snapshots__/operation-type-coder.test.js.snap
- test/typescript-generator/operation-type-coder.test.js
- **server component of support for basic auth**
- **typescript generator for security object => $.user**
> support for basic auth

- .changeset/loud-rice-double.md
- src/server/determine-module-kind.ts
- src/server/module-loader.ts
Even though we're transpiling to CJS files, the module loader was still loading the files as modules, so that cache-busting didn't work.
> fix #898, CJS files were getting loaded as modules hence more cache issues

- .changeset/hungry-emus-hope.md
- docs/usage.md
- src/server/response-builder.ts
- src/server/types.d.ts
- test/server/response-builder.test.ts
.json() now handles:
- application/json
- text/json
- text/x-json
- application/xml
- text/xml
I decided to roll up XML into `.json()` because Counterfact automatically converts a JSON object to XML. This will also remove a WTF when working with the pet store example, as it spares users from explicitly thinking about returning an XML response.
> expand .json() to include text/json and XML; fixes #918

- .changeset/yellow-oranges-promise.md
- docs/usage.md
- src/server/types.d.ts
I didn't realize until after release, but my latest change broke type checking on the argument of `.json()` and `.xml()`. 
To make the type check work I think I'm going to have to change MaybeShortcut so that ContentType is an array. I'm also going to have to change this line.
```ts
content: NeverIfEmpty<Omit<Response["content"], ContentType>>;
```
If `Response["content"]` is an array, I'll have to change `Omit` to an `OmitAll` function that loops over the arrya.
> revert a type change that made things worse

- .changeset/modern-spoons-applaud.md
- bin/counterfact.js
Version 0.44 accidentally dropped the call to the `pathsToRoutes` migration script.
> fix: Update counterfact script to correctly call pathsToRoutes

- .changeset/wet-pumas-wash.md
- src/server/context-registry.ts
- test/server/context-registry.test.ts
If an OpenApi spec has multiple paths that share the same root, but different child paths, if those parent paths are a mixture of cases, the context registry stores the contexts for the paths once (which is correct), but the `.find` operation in `context-registry` expects the map key to match the path.
For example, suppose a spec has paths of `myPets/vaccinations` as well as `mypets/visits`. Now suppose the user has created a `_.context.ts` file at `routes/myPets/_.context.ts`. When a request comes in for `myPets/vaccinations` it will find the custom context, but when the request comes in for `mypets/visits` it will fail to find the custom context because it will look for a parent path of `mypets` and nothing exists in the ContextRegistry.entries for that key.
This PR fixes the path find …
> fix(server): Update context find logic in context-registry

- .changeset/rich-bees-applaud.md
- src/server/dispatcher.ts
- src/server/module-tree.ts
- src/server/registry.ts
- test/server/module-tree.test.ts
Updates the logic in `module-tree.ts` to support a path that has multiple children that are wildcards at the same segment position. E.g.:
`/myPets/{petName}/health`
`/myPets/{petId}/records`
The PR also updates the logic in `module-tree.ts` to support a path that has multiple wildcard files at the same ending segment but with different methods. E.g.:
`/myPets/health/{id}` - GET
`/myPets/health/{enableDisable}` - PUT
> fix(server): Add support for directories with multiple wildcard children

- .changeset/selfish-numbers-matter.md
- src/server/response-builder.ts
- src/server/tools.ts
Updates the default settings for JSONSchemaFaker so the `fillProperties` setting is false. This prevents the schema faker from creating random properties in the result objects.
> feat(server): Update JSONSchemaFaker not to create fake object properties

- .changeset/long-bulldogs-stare.md
- .changeset/two-fans-collect.md
- src/server/dispatcher.ts
- src/server/registry.ts
- src/server/types.ts
- test/server/dispatcher.test.ts
Fixes #1116 
Counterfact looks at OpenAPI spec to determine the types of parameters in the query, path, or headers and make sure they are parsed to the correct type at runtime (string, number, or boolean -- we don't support arrays yet). 
When using OpenAPI / Swagger v2, the types of parameters are in the `type` property rather than `schema.type`. Counterfact wasn't looking for the `type` property so everything was being left as strings. 
Also, it didn't make a distinction between `number` and `integer`, casting all numbers to integers. With this change integers are parsed with `parseInt()` and numbers are parsed with `parseFloat()`. 
Also booleans were not parsed. Now the string "true" is parsed as `true`; any other string is `false`.
> path parameters are always strings

- .changeset/green-dodos-develop.md
- bin/counterfact.js
- src/app.ts
- src/server/config.ts
- src/server/dispatcher.ts
- src/server/response-builder.ts
- test/server/response-builder.test.ts
Here is a first take on adding the --always-fake-optionals command line option. At first I tried to add the negative case where not having this true would mean optionals are undefined, but that's not a valid test since sometimes JSONSchemaFaker provides random optionals and sometimes not (which is the allowed behavior). So I can't test the default behavior, but we should expect that turning them on is always true. Again, my trouble here is, this isn't a deterministic test since sometimes and optional can be faked even without the switch on. So it could have a false positive, but should never be negative.
Lastly, I threw in there the other two options of `fixedProbabilities` and `optionalsProbability` because from reading it seems those should be set for this to fully work. It was unclear …
> feat: Add alwaysFakeOptionals command line option

- docs/usage.md
Add documentation for the new middleware functionality to `usage.md`.
* **Middleware Functionality**
- Add a new section titled "Let's meet in the Middleware 🫸🫷" before the "No Cap Recap" section.
- Describe the purpose and usage of the middleware functionality.
- Provide an example of how to use the middleware functionality, including a sample middleware function that adds a custom header to the response.
---
For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/pmcelhaney/counterfact/pull/1238?shareId=9699d76c-41d3-4863-a4d1-6452e196eb01).
> Add documentation for middleware functionality

- .changeset/dry-socks-kiss.md
- package.json
- src/app.ts
- src/server/dispatcher.ts
- test/app.test.ts
Adds two new functions to the app: 
`createMswHandlers`
and 
`handleMswRequest`
These can be used to generate a set of mock service worker handlers that allow MSW to hand off requests to Counterfact. 
Presently this is somewhat narrowly written with Vitest Browser mode in mind where Vitest communicates with Counterfact through the Custom Commands concept where there is a bridge between the browser and node. A future update might allow the Counterfact Dispatcher to run entirely in the browser and eliminate the need for the two stage setup.
> feat: mock service worker handler ability

- .changeset/thick-rocks-clean.md
- bin/counterfact.js
- src/app.ts
- src/server/config.ts
Adds a new `buildCache` option (`-b ` or `--build-cache`) that will rebuild the local cache (implicitly generating the routes and types) without starting the server.
Fixes: https://github.com/pmcelhaney/counterfact/issues/1304
> feat: Add CLI option to build cache

- package.json
- src/server/types.ts
- test/server/types.test-d.ts
- yarn.lock
fix for https://github.com/pmcelhaney/counterfact/issues/1370
> use substring for content type parsing

- .changeset/forty-paths-tease.md
- src/server/dispatcher.ts
- src/server/koa-middleware.ts
- src/server/registry.ts
- test/server/dispatcher.proxy.test.ts
- test/server/koa-middleware.test.ts
It appears that Koa is adding an empty request body to GET requests. Get rid of it as it causes errors down the line.
> Fix an error with $.proxy() and GET requests
